# Path to file containing run-level metadata
# Usually it is a table from SRA Run Selector
sra_run_table: "config/samples.csv"

# Column names for sample and run
colname_SAMPLE: "BioSample"
colname_RUN: "Run"

# Path to key for dbGaP protected files.
# Set to null if not using protected files
dbgap_key: "config/prj_24438_D31828.ngc"

# Location for SRA URL.
# Typical options are "ncbi", "s3.us-east-1", "gs.US", etc.
sra_location: "ncbi"

tmpdir: "$TMPDIR"

# Remote databases or resources to be downloaded
downloads:
  GRCh38.d1.vd1.fa.tar.gz:
    url: "https://api.gdc.cancer.gov/data/254f697d-310d-4d7d-a27b-27fbf767a834"
    md5: "3ffbcfe2d05d43206f57f81ebb251dc9"
  gencode.v38.annotation.gtf.gz:
    url: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz"
    md5: "16fcae8ca8e488cd8056cf317d963407"
  retro.hg38.v1.gtf:
    url: "https://github.com/mlbendall/telescope_annotation_db/raw/master/builds/retro.hg38.v1/transcripts.gtf"
    md5: "c07cf115c1f957b3020efc547f3847fa"
  retro.hg38.v1.tsv.gz:
    url: "https://github.com/mlbendall/telescope_annotation_db/raw/master/builds/retro.hg38.v1/genes.tsv.gz"
    md5: "b3ca6d3705d030742255d216e25dfc1d"

sequences:
    genome: "databases/sequences/gdc38.fna"
    genome_idx: "databases/sequences/gdc38.fna.fai"
    genome_dict: "databases/sequences/gdc38.dict"

indexes:
    star: "databases/indexes/STAR_gdc38_gencode38"

annotations:
    gencode: "databases/downloads/gencode.v38.annotation.gtf.gz"
    retro: "databases/annotations/retro.hg38.v1.gtf"
    retro_tsv: "databases/annotations/retro.hg38.v1.tsv.gz"

# fasterq dump parameters
fasterq_dump_tmp:  "/fsx/projects/follicular_lymphoma_TE_atlas/runs/"

# STAR genome index parameters
splice_junction_overhang: 74
star_index_threads: 24
star_index_mem_mb: 40000
local_tmp: "$TMPDIR"

# STAR alignment parameters
star_alignment_threads: 24
outFilterMultimapNmax: 200
winAnchorMultimapNmax: 200

# TELESCOPE
telescope_threads: 4

# DIRECTORIES TO MOVE SAMPLES TO
efs_dir_telescope: "/efs/projects/follicular_lymphoma_TE_atlas/results/telescope/"
efs_dir_star: "/efs/projects/follicular_lymphoma_TE_atlas/results/star_alignment/"
